version: "2.0"
services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - docker_elk
    ulimits:
      nofile:
         soft: 65536
         hard: 65536
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.2.3
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    networks:
      - docker_elk
    depends_on:
      - elasticsearch

networks:
  docker_elk:
    driver: bridge
